server:
  port: 8891

sidecar:
  port: 10000

endpoints:
  restart:
    enabled: true
logging:
  level:
    org.springframework.security: DEBUG

zuul:
  routes:
    file: /file/**
  ignored-patterns: /oauth/**

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

multipart:
  max-file-size: 4096MB
  max-request-size: 4096MB

