server:
  port: 8891

eureka:
  instance:
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8889}/eureka/
endpoints:
  restart:
    enabled: true
logging:
  level:
    org.springframework.security: DEBUG

