server:
  port: 8888

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenzhenjia/config-repo
          basedir: target/config
  main:
    show-banner: false

